changelog:
  exclude:
    authors:
      - github-actions[bot]
  categories:
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - maintenance
        - dependencies
    - title: What's changed
      labels:
        - "*"
